version: 2.1

orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.15

jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install module deps
          command: mvn package install -Dmaven.test.skip=true

      # Download maven dependencies so that we can cache them
      # ########################
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Standard maven build and test phases
      # ########################
      - run:
          name: Verify
          command: mvn clean verify

      - store_test_results:
          path: test-results

  release:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - circleci-maven-release-orb/run-maven-release:
          mvn-release-perform-command: 'mvn --batch-mode release:perform -DdryRun=true -s my-settings.xml'
          ssh-fingerprints: 'my:ss:hf:in:ge:rp:ri:nt...'

workflows:
  version: 2
  workflow:
    jobs:
      - build
  release:
    jobs:
      - release
